# Домашняя работа №1

### Импорт библиотеки NumPy

Импорт библиотеки с общепринятым сокращением

In [1]:
import numpy as np

### Создание массивов

Создание массива (одинарного и двумерного) с перечислением элементов

In [2]:
base_array = np.array([0, 1, 2, 3, 4, 5])
print(base_array)

[0 1 2 3 4 5]


In [3]:
base_matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(base_matrix)

[[1 2 3]
 [4 5 6]]


Создание массивов, заполненных нулями, единицами. Создание единичной матрицы

In [4]:
zeros = np.zeros((3, 3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [5]:
ones = np.ones((3, 3, 3))
print(ones)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [6]:
eye_matrix = np.eye(3)
print(eye_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Создание массива, значения которого заполняются "в диапазоне".

Первый параметр — начало отсчета (включительно); 

второй параметр — конец (НЕ включительно); 

третий параметр — шаг

In [7]:
arange_array = np.arange(10, -1, -2)
print(arange_array)

[10  8  6  4  2  0]


Создание массива, заполненого "мусором". Быстрее, но требует осторожности

In [8]:
trash_array = np.empty((3,4))
print(trash_array)

[[1.29629883e-311 3.16202013e-322 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 1.39838221e-076 5.63866988e-062 2.21397261e+160]
 [1.04900717e+165 1.45194296e-051 3.83701537e+175 3.93609157e-062]]


### Демонстрация атрибутов

shape — (атрибут) кортеж размера массива по каждой оси

dtype — (атрибут) тип данных элементов массива

In [9]:
print("trash_array: ")
print(trash_array)
print("shape: ", trash_array.shape)
print("dtype: ", trash_array.dtype)

trash_array: 
[[1.29629883e-311 3.16202013e-322 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 1.39838221e-076 5.63866988e-062 2.21397261e+160]
 [1.04900717e+165 1.45194296e-051 3.83701537e+175 3.93609157e-062]]
shape:  (3, 4)
dtype:  float64


### Примеры индексирования и срезов

Пример на одномерном массиве. Получение отдельного элемента и срезы

In [10]:
example_array = np.arange(10)
print("Элемент №3:", example_array[3])
print("Элемент №3 и №5:", example_array[[3, 5]])
print("Срез от 2-ого элемента до 5-ого (вкл):", example_array[2:6])
print("Обратный порядок:", example_array[::-1]) # начало и конец по умолчаению, шаг -1

Элемент №3: 3
Элемент №3 и №5: [3 5]
Срез от 2-ого элемента до 5-ого (вкл): [2 3 4 5]
Обратный порядок: [9 8 7 6 5 4 3 2 1 0]


Пример на многомерном массиве. Получение отдельного элемента и срезы

In [11]:
example_matrix = np.arange(32)
example_matrix.shape = (2, 4, 4)
print(example_matrix)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]]


Первый индекс — номер матрицы;

второй индекс — номер строки;

третий индекс — номер столбца;

In [12]:
print("Элемент №15:", example_matrix[(0, 3, 3)])
print("Элемент №27:", example_matrix[1][2][3])
print("Элемент №6:", example_matrix[0, 1, 2])
print("2-ая строка 2-ой матрицы:", example_matrix[1, 1:2])
print("Последний столбец обеих матриц:\n", example_matrix[:,:,-1])

Элемент №15: 15
Элемент №27: 27
Элемент №6: 6
2-ая строка 2-ой матрицы: [[20 21 22 23]]
Последний столбец обеих матриц:
 [[ 3  7 11 15]
 [19 23 27 31]]


### Примеры векторных операций и базовых статистик

Создадим два двумерных массива для тестирования операций

In [13]:
first_number_array = np.arange(10)
first_number_array.shape = (2, 5)
second_number_array = np.arange(10, 20)
second_number_array.shape = (2, 5)
print(first_number_array, '\n\n', second_number_array)

[[0 1 2 3 4]
 [5 6 7 8 9]] 

 [[10 11 12 13 14]
 [15 16 17 18 19]]


In [14]:
addition = first_number_array + second_number_array
print("Сложение:\n", addition)
subtraction = first_number_array - second_number_array
print("Вычитание:\n", subtraction)
multiplication = first_number_array * second_number_array
print("Умножение:\n", multiplication)
division = second_number_array / first_number_array
print("Деление:\n", division)

Сложение:
 [[10 12 14 16 18]
 [20 22 24 26 28]]
Вычитание:
 [[-10 -10 -10 -10 -10]
 [-10 -10 -10 -10 -10]]
Умножение:
 [[  0  11  24  39  56]
 [ 75  96 119 144 171]]
Деление:
 [[        inf 11.          6.          4.33333333  3.5       ]
 [ 3.          2.66666667  2.42857143  2.25        2.11111111]]


C:\Users\Polina\AppData\Local\Temp\ipykernel_16196\2097947829.py:7: RuntimeWarning: divide by zero encountered in divide
  division = second_number_array / first_number_array


Вычисление простой статистики

In [15]:
print("Сумма значений первой матрицы:", np.sum(first_number_array))
print("Минимальное значение первой матрицы:", np.min(first_number_array))
print("Максимальное значение первой матрицы:", np.max(first_number_array))
print("Среднее значение первой матрицы:", np.mean(first_number_array))
print("Медиана первой матрицы:", np.median(first_number_array))
print("Стандартное отклонение первой матрицы:", np.std(first_number_array))
print("Дисперсия первой матрицы:", np.var(first_number_array))

Сумма значений первой матрицы: 45
Минимальное значение первой матрицы: 0
Максимальное значение первой матрицы: 9
Среднее значение первой матрицы: 4.5
Медиана первой матрицы: 4.5
Стандартное отклонение первой матрицы: 2.8722813232690143
Дисперсия первой матрицы: 8.25
